import { ICustomerRoute, ICustomerInput } from 'src/app/shared/interfaces/customer.interface';

export const ROUTES: ICustomerRoute[] = [
  {
    route: '/customer/list',
    icon: 'group',
    label: 'Listar Clientes',
  },
  {
    route: '/customer/register',
    icon: 'person_add',
    label: 'Registrar Cliente',
  },
];

const MASKS = {
  cpf: '000.000.000-00',
  cnpj: '00.000.000/0000-00',
  birth: '00/00/0000',
  cel: '(00) 00000-0000',
  cep: '00000-000',
}

export const GENERAL_INPUTS: ICustomerInput[] = [
  {
    class: 'input col-12 col-md-12',
    label: 'Nome',
    placeholder: 'Digite o nome com sobrenome',
    control: 'name',
    groupControl: '',
    type: 'text',
    required: true,
    disabled: false,
    mask: '',
  },
  {
    class: 'input col-12 col-md-4',
    label: 'CPF',
    placeholder: 'Digite o CPF',
    control: 'cpf',
    groupControl: '',
    type: 'text',
    required: true,
    disabled: false,
    mask: MASKS.cpf,
  },
  {
    class: 'input col-12 col-md-4',
    label: 'CNPJ',
    placeholder: 'Digite o CNPJ',
    control: 'cnpj',
    groupControl: '',
    type: 'text',
    required: false,
    disabled: false,
    mask: MASKS.cnpj,
  },
  {
    class: 'input col-12 col-md-4',
    label: 'Data de Nascimento',
    placeholder: 'Digite a data de nascimento',
    control: 'birth',
    groupControl: '',
    type: 'text',
    required: false,
    disabled: false,
    mask: MASKS.birth,
  },
];

export const CONTACT_INPUTS: ICustomerInput[] = [
  {
    class: 'input col-12 col-md-6',
    label: 'Celular',
    placeholder: 'Digite o celular com DDD',
    control: 'cel',
    groupControl: 'contact',
    type: 'text',
    required: true,
    disabled: false,
    mask: MASKS.cel,
  },
  {
    class: 'input col-12 col-md-6',
    label: 'E-mail',
    placeholder: 'Digite o e-mail',
    control: 'email',
    groupControl: 'contact',
    type: 'email',
    required: true,
    disabled: false,
    mask: '',
  },
];

export const ADDRESS_INPUTS: ICustomerInput[] = [
  {
    class: 'input col-12 col-md-3',
    label: 'CEP',
    placeholder: 'Digite o CEP',
    control: 'cep',
    groupControl: 'address',
    type: 'text',
    required: true,
    disabled: false,
    mask: MASKS.cep,
  },
  {
    class: 'input col-12 col-md-3',
    label: 'Estado',
    placeholder: 'Digite o estado',
    control: 'state',
    groupControl: 'address',
    type: 'text',
    required: true,
    disabled: false,
    mask: '',
  },
  {
    class: 'input col-12 col-md-3',
    label: 'Cidade',
    placeholder: 'Digite a cidade',
    control: 'city',
    groupControl: 'address',
    type: 'text',
    required: true,
    disabled: false,
    mask: '',
  },
  {
    class: 'input col-12 col-md-3',
    label: 'Bairro',
    placeholder: 'Digite o bairro',
    control: 'neighborhood',
    groupControl: 'address',
    type: 'text',
    required: true,
    disabled: false,
    mask: '',
  },
  {
    class: 'input col-12 col-md-6',
    label: 'Nome da Rua',
    placeholder: 'Digite o nome da rua',
    control: 'address',
    groupControl: 'address',
    type: 'text',
    required: true,
    disabled: false,
    mask: '',
  },
  {
    class: 'input col-12 col-md-4',
    label: 'Complemento',
    placeholder: 'Digite o complemento',
    control: 'complement',
    groupControl: 'address',
    type: 'text',
    required: false,
    disabled: false,
    mask: '',
  },
  {
    class: 'input col-12 col-md-2',
    label: 'Número',
    placeholder: 'Digite o número ou S/N',
    control: 'number',
    groupControl: 'address',
    type: 'text',
    required: false,
    disabled: false,
    mask: '',
  },
];
